# ********RoostGPT********

# Test generated by RoostGPT for test slack-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /admin.users.invite_post for http method type POST 
# RoostTestHash=c2750ab5ec
# 
# 

# ********RoostGPT********
Feature: Admin Users Invite API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Invite user to workspace with required parameters
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario Outline: Invite user to workspace with all optional parameters
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    And form field custom_message = '<custom_message>'
    And form field real_name = '<real_name>'
    And form field resend = <resend>
    And form field is_restricted = <is_restricted>
    And form field is_ultra_restricted = <is_ultra_restricted>
    And form field guest_expiration_ts = '<guest_expiration_ts>'
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario Outline: Invite user with JSON payload
    Given path '/api/admin.users.invite'
    And header token = authToken
    And header Content-Type = 'application/json'
    And request
      """
      {
        "team_id": "<team_id>",
        "email": "<email>",
        "channel_ids": "<channel_ids>",
        "custom_message": "<custom_message>",
        "real_name": "<real_name>",
        "resend": <resend>,
        "is_restricted": <is_restricted>,
        "is_ultra_restricted": <is_ultra_restricted>
      }
      """
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario: Invite user with missing required team_id parameter
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field email = 'user@example.com'
    And form field channel_ids = 'C1234567'
    When method post
    Then status != 200
    And match response.ok == false
    And match response == '#object'

  Scenario: Invite user with missing required email parameter
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = 'T1234567'
    And form field channel_ids = 'C1234567'
    When method post
    Then status != 200
    And match response.ok == false
    And match response == '#object'

  Scenario: Invite user with missing required channel_ids parameter
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = 'T1234567'
    And form field email = 'user@example.com'
    When method post
    Then status != 200
    And match response.ok == false
    And match response == '#object'

  Scenario: Invite user with missing authentication token
    Given path '/api/admin.users.invite'
    And form field team_id = 'T1234567'
    And form field email = 'user@example.com'
    And form field channel_ids = 'C1234567'
    When method post
    Then status != 200
    And match response.ok == false
    And match response == '#object'

  Scenario Outline: Invite user with invalid parameters
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    When method post
    Then status != 200
    And match response.ok == false
    And match response == '#object'

    Examples:
      | team_id      | email            | channel_ids     |
      | invalid_team | user@example.com | C1234567        |
      | T1234567     | invalid_email    | C1234567        |
      | T1234567     | user@example.com | invalid_channel |

  Scenario Outline: Invite user with boolean parameter variations
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = 'T1234567'
    And form field email = 'bool@example.com'
    And form field channel_ids = 'C1234567'
    And form field resend = <resend>
    And form field is_restricted = <is_restricted>
    And form field is_ultra_restricted = <is_ultra_restricted>
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario: Invite user with guest expiration timestamp
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = 'T1234567'
    And form field email = 'guest@example.com'
    And form field channel_ids = 'C1234567'
    And form field is_ultra_restricted = true
    And form field guest_expiration_ts = '1672531200'
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'

  Scenario: Invite user with long custom message
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = 'T1234567'
    And form field email = 'longmsg@example.com'
    And form field channel_ids = 'C1234567'
    And form field custom_message = 'This is a very long custom message that contains detailed information about the workspace invitation and what the user can expect when they join our team and start collaborating with us.'
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'

  Scenario: Invite user with special characters in real name
    Given path '/api/admin.users.invite'
    And header token = authToken
    And form field team_id = 'T1234567'
    And form field email = 'special@example.com'
    And form field channel_ids = 'C1234567'
    And form field real_name = 'José María O\'Connor-Smith'
    When method post
    Then status 200
    And match response.ok == true
    And match response == '#object'
