# ********RoostGPT********

# Test generated by RoostGPT for test slack-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /admin.users.invite_post for http method type POST 
# RoostTestHash=adb63dd000
# 
# 

# ********RoostGPT********
Feature: Admin Users Invite API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Invite user to workspace with valid data
    Given path '/api/admin.users.invite'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    And form field custom_message = '<custom_message>'
    And form field real_name = '<real_name>'
    And form field resend = <resend>
    And form field is_restricted = <is_restricted>
    And form field is_ultra_restricted = <is_ultra_restricted>
    And form field guest_expiration_ts = '<guest_expiration_ts>'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario Outline: Invite user with required fields only
    Given path '/api/admin.users.invite'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario Outline: Invite user with JSON content type
    Given path '/api/admin.users.invite'
    And header Content-Type = 'application/json'
    And request
      """
      {
        "team_id": "<team_id>",
        "email": "<email>",
        "channel_ids": "<channel_ids>",
        "custom_message": "<custom_message>",
        "real_name": "<real_name>",
        "resend": <resend>,
        "is_restricted": <is_restricted>,
        "is_ultra_restricted": <is_ultra_restricted>,
        "guest_expiration_ts": "<guest_expiration_ts>"
      }
      """
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario: Invite user without authorization token
    Given path '/api/admin.users.invite'
    And configure headers = null
    And form field team_id = 'T1234567890'
    And form field email = 'noauth@example.com'
    And form field channel_ids = 'C1234567890'
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

  Scenario Outline: Invite user with missing required fields
    Given path '/api/admin.users.invite'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

    Examples:
      | team_id     | email            | channel_ids |
      |             | test@example.com | C1234567890 |
      | T1234567890 |                  | C1234567890 |
      | T1234567890 | test@example.com |             |

  Scenario Outline: Invite user with invalid email format
    Given path '/api/admin.users.invite'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

    Examples:
      | team_id     | email         | channel_ids |
      | T1234567890 | invalid-email | C1234567890 |
      | T1234567890 | @example.com  | C1234567890 |
      | T1234567890 | test@.com     | C1234567890 |

  Scenario Outline: Invite user with boolean field variations
    Given path '/api/admin.users.invite'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    And form field resend = <resend>
    And form field is_restricted = <is_restricted>
    And form field is_ultra_restricted = <is_ultra_restricted>
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario: Invite user with multiple channel IDs
    Given path '/api/admin.users.invite'
    And form field team_id = 'T1234567890'
    And form field email = 'multichannel@example.com'
    And form field channel_ids = 'C1111111111,C2222222222,C3333333333'
    And form field real_name = 'Multi Channel User'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

  Scenario: Invite guest user with expiration timestamp
    Given path '/api/admin.users.invite'
    And form field team_id = 'T1234567890'
    And form field email = 'expiring@example.com'
    And form field channel_ids = 'C1234567890'
    And form field is_ultra_restricted = true
    And form field guest_expiration_ts = '1672531200'
    And form field real_name = 'Expiring Guest'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

  Scenario: Invite user with custom message
    Given path '/api/admin.users.invite'
    And form field team_id = 'T1234567890'
    And form field email = 'custom@example.com'
    And form field channel_ids = 'C1234567890'
    And form field custom_message = 'Welcome! We are excited to have you join our team. Please let us know if you have any questions.'
    And form field real_name = 'Custom Message User'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'
