# ********RoostGPT********

# Test generated by RoostGPT for test slack-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /admin.users.invite_post for http method type POST 
# RoostTestHash=adb63dd000
# 
# 

# ********RoostGPT********
Feature: Admin Users Invite API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Authorization: #(karate.properties['AUTH_TOKEN']) }

  Scenario Outline: Invite user to workspace with valid data
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    And form field custom_message = '<custom_message>'
    And form field real_name = '<real_name>'
    And form field resend = <resend>
    And form field is_restricted = <is_restricted>
    And form field is_ultra_restricted = <is_ultra_restricted>
    And form field guest_expiration_ts = '<guest_expiration_ts>'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario Outline: Invite user with minimal required fields
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = '<team_id>'
    And form field email = '<email>'
    And form field channel_ids = '<channel_ids>'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario Outline: Invite user with JSON content type
    Given path '/admin.users.invite'
    And header Content-Type = 'application/json'
    And request
      """
      {
        "team_id": "<team_id>",
        "email": "<email>",
        "channel_ids": "<channel_ids>",
        "custom_message": "<custom_message>",
        "real_name": "<real_name>",
        "resend": <resend>,
        "is_restricted": <is_restricted>,
        "is_ultra_restricted": <is_ultra_restricted>,
        "guest_expiration_ts": "<guest_expiration_ts>"
      }
      """
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario: Invite user without required team_id field
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field email = 'test@example.com'
    And form field channel_ids = 'C1234567890'
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

  Scenario: Invite user without required email field
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field channel_ids = 'C1234567890'
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

  Scenario: Invite user without required channel_ids field
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field email = 'test@example.com'
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

  Scenario: Invite user without authorization token
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field email = 'test@example.com'
    And form field channel_ids = 'C1234567890'
    And configure headers = null
    When method post
    Then status != 200
    And match response.ok == false
    And match response.ok == '#boolean'

  Scenario Outline: Invite user with boolean field variations
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field email = '<email>'
    And form field channel_ids = 'C1234567890'
    And form field resend = <resend>
    And form field is_restricted = <is_restricted>
    And form field is_ultra_restricted = <is_ultra_restricted>
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

    Examples:
      | read('admin.users.invite_post.csv') |

  Scenario: Invite user with guest expiration timestamp
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field email = 'guest@example.com'
    And form field channel_ids = 'C1234567890'
    And form field is_ultra_restricted = true
    And form field guest_expiration_ts = '1672531200'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

  Scenario: Invite user with multiple channel IDs
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field email = 'multi@example.com'
    And form field channel_ids = 'C1234567890,C0987654321,C1111111111'
    And form field real_name = 'Multi Channel User'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'

  Scenario: Invite user with custom message
    Given path '/admin.users.invite'
    And header Content-Type = 'application/x-www-form-urlencoded'
    And form field team_id = 'T1234567890'
    And form field email = 'custom@example.com'
    And form field channel_ids = 'C1234567890'
    And form field custom_message = 'Welcome! We are excited to have you join our team. Please feel free to reach out if you have any questions.'
    And form field real_name = 'Custom Message User'
    When method post
    Then status 200
    And match response.ok == true
    And match response.ok == '#boolean'
