# ********RoostGPT********

# Test generated by RoostGPT for test slack-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /team.info_get for http method type GET 
# RoostTestHash=63835c9862
# 
# 

# ********RoostGPT********
Feature: Team Info API

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Get team information with valid parameters
    Given path '/api/team.info'
    And param token = authToken
    And param team = '<team>'
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    And match response.team.id == '#string'
    And match response.team.id == '#regex ^[TE][A-Z0-9]{8,}$'
    And match response.team.name == '#string'
    And match response.team.domain == '#string'
    And match response.team.email_domain == '#string'
    And match response.team.icon == '#object'
    And match response.team.icon.image_34 == '##string'
    And match response.team.icon.image_44 == '##string'
    And match response.team.icon.image_68 == '##string'
    And match response.team.icon.image_88 == '##string'
    And match response.team.icon.image_102 == '##string'
    And match response.team.icon.image_132 == '##string'
    And match response.team.icon.image_230 == '##string'
    And match response.team.icon.image_default == '##boolean'
    And match response.team.enterprise_id == '##string'
    And match response.team.enterprise_name == '##string'
    And match response.team.archived == '##boolean'
    And match response.team.avatar_base_url == '##string'
    And match response.team.created == '##number'
    And match response.team.date_create == '##number'
    And match response.team.deleted == '##boolean'
    And match response.team.description == '#? _ == null || typeof _ == "string"'
    And match response.team.discoverable == '##array'
    And match response.team.has_compliance_export == '##boolean'
    And match response.team.is_assigned == '##boolean'
    And match response.team.is_enterprise == '##number'
    And match response.team.is_over_storage_limit == '##boolean'
    And match response.team.limit_ts == '##number'
    And match response.team.locale == '##string'
    And match response.team.messages_count == '##number'
    And match response.team.msg_edit_window_mins == '##number'
    And match response.team.over_integrations_limit == '##boolean'
    And match response.team.over_storage_limit == '##boolean'
    And match response.team.pay_prod_cur == '##string'
    And match response.team.plan == '##string'
    And match response.team.primary_owner == '##object'
    And match response.team.sso_provider == '##object'
    And match response.team.external_org_migrations == '##object'

    Examples:
      | read('team.info_get.csv') |

  Scenario: Get current team information without team parameter
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    And match response.team.id == '#string'
    And match response.team.id == '#regex ^[TE][A-Z0-9]{8,}$'
    And match response.team.name == '#string'
    And match response.team.domain == '#string'
    And match response.team.email_domain == '#string'
    And match response.team.icon == '#object'

  Scenario: Validate team object enterprise_id pattern when present
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    * if (response.team.enterprise_id) karate.match(response.team.enterprise_id, '#regex ^[E][A-Z0-9]{8,}$')

  Scenario: Validate team object primary_owner structure when present
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    * if (response.team.primary_owner) karate.match(response.team.primary_owner.id, '#string')
    * if (response.team.primary_owner) karate.match(response.team.primary_owner.email, '#string')

  Scenario: Validate team object sso_provider structure when present
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    * if (response.team.sso_provider) karate.match(response.team.sso_provider.label, '##string')
    * if (response.team.sso_provider) karate.match(response.team.sso_provider.name, '##string')
    * if (response.team.sso_provider) karate.match(response.team.sso_provider.type, '##string')

  Scenario: Validate team object external_org_migrations structure when present
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    * if (response.team.external_org_migrations) karate.match(response.team.external_org_migrations.date_updated, '#number')
    * if (response.team.external_org_migrations) karate.match(response.team.external_org_migrations.current, '#array')
    * if (response.team.external_org_migrations && response.team.external_org_migrations.current.length > 0) karate.match('each response.team.external_org_migrations.current[*].team_id', '#string')
    * if (response.team.external_org_migrations && response.team.external_org_migrations.current.length > 0) karate.match('each response.team.external_org_migrations.current[*].date_started', '#number')

  Scenario: Validate team plan enum values when present
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    * if (response.team.plan) karate.match(response.team.plan, '#regex ^(|std|plus|compliance|enterprise)$')

  Scenario Outline: Handle authentication errors
    Given path '/api/team.info'
    And param token = '<token>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'

    Examples:
      | token         | status | error        |
      | invalid_token |    401 | invalid_auth |
      | null          |    401 | not_authed   |

  Scenario Outline: Handle various error responses
    Given path '/api/team.info'
    And param token = '<token>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'
    And match response.callstack == '##string'

    Examples:
      | token          | status | error            |
      | revoked_token  |    401 | token_revoked    |
      | inactive_token |    401 | account_inactive |
      | no_perm_token  |    403 | no_permission    |

  Scenario: Handle invalid argument name error
    Given path '/api/team.info'
    And param token = authToken
    And param invalid_param = 'test'
    When method GET
    Then status 400
    And match response.ok == false
    And match response.error == 'invalid_arg_name'

  Scenario: Handle request timeout error
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 408
    And match response.ok == false
    And match response.error == 'request_timeout'

  Scenario: Handle upgrade required error
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 426
    And match response.ok == false
    And match response.error == 'upgrade_required'

  Scenario: Handle fatal error
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 500
    And match response.ok == false
    And match response.error == 'fatal_error'

  Scenario: Handle team added to org error
    Given path '/api/team.info'
    And param token = authToken
    When method GET
    Then status 400
    And match response.ok == false
    And match response.error == 'team_added_to_org'

  Scenario: Handle invalid JSON error
    Given path '/api/team.info'
    And param token = authToken
    And header Content-Type = 'application/json'
    And request 'invalid json'
    When method POST
    Then status 400
    And match response.ok == false
    And match response.error == 'invalid_json'

  Scenario: Handle JSON not object error
    Given path '/api/team.info'
    And param token = authToken
    And header Content-Type = 'application/json'
    And request '"not an object"'
    When method POST
    Then status 400
    And match response.ok == false
    And match response.error == 'json_not_object'
