# ********RoostGPT********

# Test generated by RoostGPT for test slack-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /team.info_get for http method type GET 
# RoostTestHash=0df2be9624
# 
# 

# ********RoostGPT********
Feature: Team Info API Testing

  Background:
    * def urlBase = karate.properties['API_HOST']
    * url urlBase
    * configure headers = { Authorization: 'Bearer ' + karate.properties['AUTH_TOKEN'] }

  Scenario Outline: Get team information with valid parameters
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method get
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    And match response.team.id == '#string'
    And match response.team.id == '#regex ^[TE][A-Z0-9]{8,}$'
    And match response.team.name == '#string'
    And match response.team.domain == '#string'
    And match response.team.email_domain == '#string'
    And match response.team.icon == '#object'
    And match response.team.icon.image_102 == '##string'
    And match response.team.icon.image_132 == '##string'
    And match response.team.icon.image_230 == '##string'
    And match response.team.icon.image_34 == '##string'
    And match response.team.icon.image_44 == '##string'
    And match response.team.icon.image_68 == '##string'
    And match response.team.icon.image_88 == '##string'
    And match response.team.icon.image_default == '##boolean'
    And match response.team.archived == '##boolean'
    And match response.team.avatar_base_url == '##string'
    And match response.team.created == '##number'
    And match response.team.date_create == '##number'
    And match response.team.deleted == '##boolean'
    And match response.team.description == '#? _ == null || typeof _ == "string"'
    And match response.team.discoverable == '##object'
    And match response.team.enterprise_id == '##string'
    And match response.team.enterprise_name == '##string'
    And match response.team.external_org_migrations == '##object'
    And match response.team.external_org_migrations.current == '##array'
    And match response.team.external_org_migrations.date_updated == '##number'
    And match each response.team.external_org_migrations.current[*].team_id == '#string'
    And match each response.team.external_org_migrations.current[*].date_started == '#number'
    And match response.team.has_compliance_export == '##boolean'
    And match response.team.is_assigned == '##boolean'
    And match response.team.is_enterprise == '##number'
    And match response.team.is_over_storage_limit == '##boolean'
    And match response.team.limit_ts == '##number'
    And match response.team.locale == '##string'
    And match response.team.messages_count == '##number'
    And match response.team.msg_edit_window_mins == '##number'
    And match response.team.over_integrations_limit == '##boolean'
    And match response.team.over_storage_limit == '##boolean'
    And match response.team.pay_prod_cur == '##string'
    And match response.team.plan == '##string'
    And match response.team.primary_owner == '##object'
    And match response.team.primary_owner.id == '##string'
    And match response.team.primary_owner.email == '##string'
    And match response.team.sso_provider == '##object'
    And match response.team.sso_provider.label == '##string'
    And match response.team.sso_provider.name == '##string'
    And match response.team.sso_provider.type == '##string'

    Examples:
      | read('team.info_get.csv') |

  Scenario Outline: Get team information with required token only
    Given path '/api/team.info'
    And param token = '<token>'
    When method get
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    And match response.team.id == '#string'
    And match response.team.name == '#string'
    And match response.team.domain == '#string'
    And match response.team.email_domain == '#string'
    And match response.team.icon == '#object'

    Examples:
      | read('team.info_get.csv') |

  Scenario Outline: Get team information with invalid authentication
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method get
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'
    And match response.callstack == '##string'

    Examples:
      | token          | team   | status | error            |
      | invalid_token  | T12345 |    401 | invalid_auth     |
      |                | T12345 |    401 | not_authed       |
      | revoked_token  | T12345 |    401 | token_revoked    |
      | inactive_token | T12345 |    401 | account_inactive |

  Scenario Outline: Get team information with various error conditions
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method get
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'

    Examples:
      | token       | team    | status | error             |
      | valid_token | invalid |    403 | no_permission     |
      | valid_token | T12345  |    400 | invalid_arg_name  |
      | valid_token | T12345  |    400 | invalid_array_arg |
      | valid_token | T12345  |    400 | invalid_charset   |
      | valid_token | T12345  |    400 | invalid_form_data |
      | valid_token | T12345  |    400 | invalid_post_type |
      | valid_token | T12345  |    400 | missing_post_type |
      | valid_token | T12345  |    400 | team_added_to_org |
      | valid_token | T12345  |    400 | invalid_json      |
      | valid_token | T12345  |    400 | json_not_object   |
      | valid_token | T12345  |    408 | request_timeout   |
      | valid_token | T12345  |    426 | upgrade_required  |
      | valid_token | T12345  |    500 | fatal_error       |

  Scenario: Validate team ID pattern for enterprise
    Given path '/api/team.info'
    And param token = 'valid_token'
    When method get
    Then status 200
    And match response.team.id == '#regex ^[TE][A-Z0-9]{8,}$'
    And if (response.team.enterprise_id) match response.team.enterprise_id == '#regex ^[E][A-Z0-9]{8,}$'

  Scenario: Validate team plan enum values
    Given path '/api/team.info'
    And param token = 'valid_token'
    When method get
    Then status 200
    And if (response.team.plan) match response.team.plan == '#? _ == "" || _ == "std" || _ == "plus" || _ == "compliance" || _ == "enterprise"'

  Scenario: Validate avatar base URL format
    Given path '/api/team.info'
    And param token = 'valid_token'
    When method get
    Then status 200
    And if (response.team.avatar_base_url) match response.team.avatar_base_url == '#regex ^https?://.*'

  Scenario: Validate external org migrations structure
    Given path '/api/team.info'
    And param token = 'valid_token'
    When method get
    Then status 200
    And if (response.team.external_org_migrations) match response.team.external_org_migrations.current == '#array'
    And if (response.team.external_org_migrations) match response.team.external_org_migrations.date_updated == '#number'
    And if (response.team.external_org_migrations && response.team.external_org_migrations.current.length > 0) match each response.team.external_org_migrations.current[*].team_id == '#string'
    And if (response.team.external_org_migrations && response.team.external_org_migrations.current.length > 0) match each response.team.external_org_migrations.current[*].date_started == '#number'
