# ********RoostGPT********

# Test generated by RoostGPT for test slack-api using AI Type Claude AI and AI Model claude-sonnet-4-20250514
# 
# Feature file generated for /team.info_get for http method type GET 
# RoostTestHash=0df2be9624
# 
# 

# ********RoostGPT********
Feature: Team Info API Testing

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Get team information with valid token
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team == '#object'
    And match response.team.id == '#string'
    And match response.team.id == '#regex ^[TE][A-Z0-9]{8,}$'
    And match response.team.name == '#string'
    And match response.team.domain == '#string'
    And match response.team.email_domain == '#string'
    And match response.team.icon == '#object'
    And match response.team.icon.image_102 == '##string'
    And match response.team.icon.image_132 == '##string'
    And match response.team.icon.image_230 == '##string'
    And match response.team.icon.image_34 == '##string'
    And match response.team.icon.image_44 == '##string'
    And match response.team.icon.image_68 == '##string'
    And match response.team.icon.image_88 == '##string'
    And match response.team.icon.image_default == '##boolean'
    And match response.team.archived == '##boolean'
    And match response.team.avatar_base_url == '##string'
    And match response.team.created == '##number'
    And match response.team.date_create == '##number'
    And match response.team.deleted == '##boolean'
    And match response.team.description == '#? _ == null || typeof _ == "string"'
    And match response.team.discoverable == '##object'
    And match response.team.enterprise_id == '##string'
    And match response.team.enterprise_name == '##string'
    And match response.team.external_org_migrations == '##object'
    And match response.team.external_org_migrations.date_updated == '##number'
    And match response.team.external_org_migrations.current == '##[]'
    And match each response.team.external_org_migrations.current[*].team_id == '#string'
    And match each response.team.external_org_migrations.current[*].date_started == '#number'
    And match response.team.has_compliance_export == '##boolean'
    And match response.team.is_assigned == '##boolean'
    And match response.team.is_enterprise == '##number'
    And match response.team.is_over_storage_limit == '##boolean'
    And match response.team.limit_ts == '##number'
    And match response.team.locale == '##string'
    And match response.team.messages_count == '##number'
    And match response.team.msg_edit_window_mins == '##number'
    And match response.team.over_integrations_limit == '##boolean'
    And match response.team.over_storage_limit == '##boolean'
    And match response.team.pay_prod_cur == '##string'
    And match response.team.plan == '##string'
    And match response.team.primary_owner == '##object'
    And match response.team.primary_owner.id == '##string'
    And match response.team.primary_owner.email == '##string'
    And match response.team.sso_provider == '##object'
    And match response.team.sso_provider.label == '##string'
    And match response.team.sso_provider.name == '##string'
    And match response.team.sso_provider.type == '##string'

    Examples:
      | token                    | team      |
      | xoxb-valid-token-123     |           |
      | xoxb-valid-token-456     | T12345    |
      | xoxp-user-token-789      | E1234567  |

  Scenario Outline: Get team information with invalid authentication
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'

    Examples:
      | token                | team    | status | error           |
      | invalid-token        |         | 200    | invalid_auth    |
      | expired-token        | T12345  | 200    | token_revoked   |
      |                      |         | 200    | not_authed      |
      | inactive-token       | E12345  | 200    | account_inactive|

  Scenario Outline: Get team information with missing required parameters
    Given path '/api/team.info'
    And param team = '<team>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'

    Examples:
      | team    | status | error      |
      |         | 200    | not_authed |
      | T12345  | 200    | not_authed |

  Scenario Outline: Get team information with invalid parameters
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'

    Examples:
      | token                | team           | status | error           |
      | xoxb-valid-token     | invalid-team   | 200    | invalid_arg_name|
      | xoxb-valid-token     | 123            | 200    | invalid_arg_name|

  Scenario Outline: Get team information with permission errors
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'

    Examples:
      | token                    | team    | status | error         |
      | xoxb-no-permission-token |         | 200    | no_permission |
      | xoxb-limited-scope-token | T12345  | 200    | no_permission |

  Scenario Outline: Get team information with system errors
    Given path '/api/team.info'
    And param token = '<token>'
    And param team = '<team>'
    When method GET
    Then status <status>
    And match response.ok == false
    And match response.error == '<error>'
    And match response.callstack == '##string'

    Examples:
      | token            | team    | status | error           |
      | xoxb-valid-token |         | 200    | fatal_error     |
      | xoxb-valid-token | T12345  | 200    | request_timeout |
      | xoxb-valid-token | E12345  | 200    | upgrade_required|

  Scenario: Validate enterprise ID pattern in successful response
    Given path '/api/team.info'
    And param token = 'xoxb-valid-enterprise-token'
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team.enterprise_id == '#regex ^[E][A-Z0-9]{8,}$'

  Scenario: Validate team plan enum values in successful response
    Given path '/api/team.info'
    And param token = 'xoxb-valid-token'
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team.plan == '#? _ == "" || _ == "std" || _ == "plus" || _ == "compliance" || _ == "enterprise"'

  Scenario: Validate team ID pattern in successful response
    Given path '/api/team.info'
    And param token = 'xoxb-valid-token'
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team.id == '#regex ^[TE][A-Z0-9]{8,}$'

  Scenario: Validate avatar_base_url format in successful response
    Given path '/api/team.info'
    And param token = 'xoxb-valid-token'
    When method GET
    Then status 200
    And match response.ok == true
    And match response.team.avatar_base_url == '##string'
